/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ai/manifest.md": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/manifest.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
                400: components["responses"]["BadRequest"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
                400: components["responses"]["BadRequest"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/views/{view_key}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    view_key: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PublicViewResults"];
                    };
                };
                400: components["responses"]["BadRequest"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/units/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PublicUnitDetail"];
                    };
                };
                400: components["responses"]["BadRequest"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/listings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PublicListingDetail"];
                    };
                };
                400: components["responses"]["BadRequest"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["PublicProject"][];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PublicProjectDetail"];
                    };
                };
                400: components["responses"]["BadRequest"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/projects/{id}/stacking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PublicStackingBuilding"][];
                    };
                };
                400: components["responses"]["BadRequest"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["PublicUnitCard"][];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/listings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["PublicListingCard"][];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/promotions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["PublicPromotion"][];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/promotions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PublicPromotion"];
                    };
                };
                400: components["responses"]["BadRequest"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PublicViewResults: {
            view: {
                key: string;
                name: unknown;
                /** @enum {string} */
                entity: "unit" | "listing";
            };
            items: (components["schemas"]["PublicUnitCard"] | components["schemas"]["PublicListingCard"])[];
        };
        PublicUnitDetail: {
            id: string;
            unit_number: string;
            type: string;
            project_id: string | null;
            building_id: string | null;
            floor_number: number | null;
            rooms: number | null;
            area: string | null;
            price: components["schemas"]["PublicPrice"];
            status: components["schemas"]["PublicStatusBadge"];
            promotion_badges: components["schemas"]["LabelText"][];
            cover_url?: string;
            characteristic_sections: components["schemas"]["CharacteristicSection"][];
            media: {
                [key: string]: unknown;
            }[];
        };
        PublicListingDetail: {
            id: string;
            type: string;
            reference: string | null;
            project_id: string | null;
            floor_number: number | null;
            rooms: number | null;
            area: string | null;
            address?: components["schemas"]["Address"];
            price: components["schemas"]["PublicPrice"];
            status: components["schemas"]["PublicStatusBadge"];
            cover_url?: string;
            characteristic_sections: components["schemas"]["CharacteristicSection"][];
            media: {
                [key: string]: unknown;
            }[];
        };
        PublicProject: {
            id: string;
            name: string;
            address?: components["schemas"]["Address"] | null;
            status: string;
            status_label: components["schemas"]["LabelText"];
            status_color: string | null;
            currency: string;
            media: {
                [key: string]: unknown;
            }[];
            published_at: string | null;
            unit_summary: components["schemas"]["UnitSummary"];
            price_range?: components["schemas"]["PriceRange"];
            price_per_sqm_range?: components["schemas"]["PriceRange"];
            area_range: components["schemas"]["PriceRange"];
            active_promotion_count: number;
            building_count: number;
        };
        PublicProjectDetail: {
            id: string;
            name: string;
            address?: components["schemas"]["Address"] | null;
            status: string;
            status_label: components["schemas"]["LabelText"];
            status_color: string | null;
            currency: string;
            media: {
                [key: string]: unknown;
            }[];
            published_at: string | null;
            unit_summary: components["schemas"]["UnitSummary"];
            price_range?: components["schemas"]["PriceRange"];
            price_per_sqm_range?: components["schemas"]["PriceRange"];
            area_range: components["schemas"]["PriceRange"];
            active_promotion_count: number;
            building_count: number;
            characteristic_sections: components["schemas"]["CharacteristicSection"][];
        };
        PublicStackingBuilding: {
            building_id: string;
            building_name: string;
            floors: components["schemas"]["PublicStackingFloor"][];
        };
        PublicUnitCard: {
            id: string;
            unit_number: string;
            type: string;
            project_id: string | null;
            building_id: string | null;
            floor_number: number | null;
            rooms: number | null;
            area: string | null;
            price: components["schemas"]["PublicPrice"];
            status: components["schemas"]["PublicStatusBadge"];
            promotion_badges: components["schemas"]["LabelText"][];
            cover_url?: string;
        };
        PublicListingCard: {
            id: string;
            type: string;
            reference: string | null;
            project_id: string | null;
            floor_number: number | null;
            rooms: number | null;
            area: string | null;
            address?: components["schemas"]["Address"];
            price: components["schemas"]["PublicPrice"];
            status: components["schemas"]["PublicStatusBadge"];
            cover_url?: string;
        };
        PublicPromotion: {
            id: string;
            name: components["schemas"]["LabelText"];
            description: components["schemas"]["LabelText"] | null;
            discount: {
                /** @enum {string} */
                kind: "percent" | "amount";
                value: string;
                currency: string | null;
            } | null;
            starts_at: string | null;
            ends_at: string | null;
            affected_unit_count: number;
        };
        Error: {
            error: string;
            code: string;
            details?: {
                [key: string]: unknown;
            };
        };
        PublicPrice: {
            /** @enum {string} */
            mode: "visible" | "on_request";
            currency: string;
            current?: string;
            effective?: string;
            discount_pct?: number;
            per_sqm?: string;
        };
        PublicStatusBadge: {
            /** @enum {string} */
            state: "available" | "unavailable";
            /** @enum {string} */
            core_status: "available" | "reserved" | "sold";
            label?: components["schemas"]["LabelText"];
            color?: string;
        };
        LabelText: string;
        CharacteristicSection: {
            /** @enum {string} */
            level: "unit" | "building" | "project";
            groups: components["schemas"]["CharacteristicGroup"][];
        };
        Address: {
            country: string;
            admin1?: components["schemas"]["AddressComponent"];
            admin2?: components["schemas"]["AddressComponent"];
            admin3?: components["schemas"]["AddressComponent"];
            admin4?: components["schemas"]["AddressComponent"];
            street?: string;
            house_number?: string;
            postal_code?: string;
            unparsed?: string;
            point?: components["schemas"]["GeoPoint"];
        };
        UnitSummary: {
            available: number;
            reserved: number;
            sold: number;
            blocked: number;
            total: number;
        };
        PriceRange: {
            min: string | null;
            max: string | null;
        };
        PublicStackingFloor: {
            floor_number: number | null;
            cells: components["schemas"]["PublicStackingCell"][];
        };
        CharacteristicGroup: {
            key: string;
            label: components["schemas"]["LabelText"];
            fields: components["schemas"]["CharacteristicField"][];
        };
        AddressComponent: {
            key: string;
            label: string;
        };
        GeoPoint: {
            lat: number;
            lon: number;
        };
        PublicStackingCell: {
            line_key: string | null;
            unit_id?: string;
            unit_number?: string;
            area?: string;
            rooms?: number;
            cover_url?: string;
            price?: components["schemas"]["PublicPrice"];
            status: components["schemas"]["PublicStatusBadge"];
        };
        CharacteristicField: {
            key: string;
            label: components["schemas"]["LabelText"];
            value: string | number | boolean | string[] | components["schemas"]["LabelText"];
            unit?: string;
        };
    };
    responses: {
        /** @description Bad request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
